backend/src/controllers/order.ts, backend/src/controllers/orderItem_repository.ts, backend/src/controllers/order_repository.ts, backend/src/controllers/shop.ts, backend/src/controllers/user.ts, backend/src/routes/order.ts, backend/src/routes/shop.ts, backend/src/routes/user.ts, lib/shared_types.ts
1. Revise createOrder: allows clients to create orders along with associated order items in a single request
2. Add getOrdersByUser: extract from getOrders
3. Add getOrdersByShop: extract from getOrders
4. OrderStatus add "cancelled"
=> Backend: order controller - revise createOrder, add getOrdersByUser and getOrdersByShop

backend/src/controllers/meal.ts, backend/src/controllers/meal_repository.ts, backend/src/controllers/review.ts, backend/src/controllers/review_repository.ts, backend/src/controllers/shop.ts, backend/src/controllers/shop_repository.ts, backend/src/routes/shop.ts, lib/shared_types_shop.ts
實作了上次討論時shop需要的api，也已經test過確認功能沒問題了
=> implemet some shop api 

backend/src/controllers/user.ts, lib/shared_types.ts
=> Backend: add user id in the login response data

backend/src/controllers/user.ts
1. only sum orders whose status is finished
2. check if year and month is valid
=> Backend: fix User getBalance

backend/src/controllers/shop.ts, backend/src/routes/shop.ts, lib/shared_types.ts
新的api: GET api/shop
會回傳各個類別的店家有幾間
=> Backend: add new api (getShopsCategory)

backend/src/controllers/shop.ts
1. check if year and month is valid for getRevenue and getRevenueDetails in Shop controller
2. only count finished orders for getRevenue and getRevenueDetails in Shop controller
=> Backend: check if year and month is valid & only count finished orders for getRevenue in Shop controller

backend/src/controllers/order.ts
1. check if user_id, shop_id, meal_id exist for createOrder
2. check if meal_id belongs to shop_id for createOrder
=> Backend: check if user_id, shop_id, meal_id exist, and meal_id belongs to shop_id for createOrder

frontend/src/pages/BuyPage/CartPage/CartPage.tsx, frontend/src/pages/BuyPage/CartPage/_components/CartItem.tsx, frontend/src/pages/BuyPage/CartPage/_components/CheckoutDialog.tsx, frontend/src/pages/OrderPage/BuyerOrderPage/BuyerOrderPage.tsx, frontend/src/utils/client.ts
1. connect the whole ordering workflow now.
2. login authetication check.
3. remove cart items done..
4. keep shopping done.
5. order confirmation done.
6. in short, all cart related things are done.
=> Frontend: feature/cartpages

backend/src/controllers/shop.ts, backend/src/controllers/shop_repository.ts, backend/src/routes/shop.ts
將GET /api/shop/:id的id改成輸入user_id
=> add getShopByUserId API

frontend/src/pages/BuyPage/CartPage/CartPage.tsx, frontend/src/pages/BuyPage/CartPage/_components/CartItem.tsx, frontend/src/pages/BuyPage/CartPage/_components/CheckoutDialog.tsx
1. turn the data structure in the cart page into correct form.
2. we can read all orders from different shops now.
=> Frontend: adjust data structure in the cart page

backend/src/controllers/shop.ts, backend/src/controllers/user.ts
1. remove await of sendEmailToUser
2. remove await of sendEmailToShop
=> Backend: remove await of sendEmail

backend/src/controllers/shop.ts, lib/shared_types.ts
1. add meal price and revenue for every meal
=> Backend: revise return content of getRevenueDetails

frontend/src/pages/OrderPage/BuyerOrderPage/BuyerOrderPage.tsx, frontend/src/pages/OrderPage/BuyerOrderPage/_components/BuyerOrderDetail.tsx, frontend/src/pages/OrderPage/BuyerOrderPage/_components/BuyerOrderItem.tsx
1. display newest orders first.
2. RWD UI DONE.
3. Add new function that we can "再次購買" in order details.
=> Frontend: buyer orderpage RWD UI DONE

frontend/src/pages/OrderPage/SalerOrderPage/SalerOrderPage.tsx, frontend/src/pages/OrderPage/SalerOrderPage/_components/SalerOrderItem.tsx
1. Saler OrderPage RWD UI DONE
=> Frotend: Saler OrderPage RWD UI DONE

backend/src/test/controller/user_repository.test.ts
=> Backend: add unit test for userRepo

backend/src/test/controller/orderItem_repository.test.ts
=> Backend: add unit test for orderItemRepo

backend/src/controllers/shop.ts, backend/src/test/controller/shop.test.ts
=> Backend: add unit test for shop

backend/src/test/controller/shop_repository.test.ts
=> Backend: add unit test for shopRepo

backend/src/test/controller/order.test.ts
=> Backend: add unit test for order

frontend/src/App.tsx, frontend/src/components/MenuFunctions/MenuFunctions.tsx, frontend/src/pages/OrderPage/SalerOrderPage/SalerOrderPage.tsx, frontend/src/pages/UserPage/SignInPage/SignInPage.tsx, frontend/src/pages/UserPage/SignUpPage/SignUpPage.tsx, frontend/src/pages/UserPage/UserPage.tsx
add some error toast for 登入 and 訂單
=> Error toast

frontend/src/pages/OrderPage/SalerOrderPage/SalerOrderPage.tsx, frontend/src/pages/UserPage/SignInPage/SignInPage.tsx, frontend/src/pages/UserPage/SignUpPage/SignUpPage.tsx, frontend/src/pages/UserPage/UserPage.tsx
user edit:
1. password must be longer than 8 
2. click edit button to edit password
=> user edit done

frontend/src/pages/BuyPage/CartPage/CartPage.tsx, frontend/src/pages/BuyPage/CartPage/_components/CartItem.tsx, frontend/src/pages/BuyPage/CartPage/_components/CheckoutDialog.tsx
1. Cart Related-Page RWD UI DONE
=> Frontend: CartPage RWD UI DONE

frontend/src/components/Header/Login/index.tsx, frontend/src/components/Header/Login/main.css, frontend/src/components/Header/TsmcSushi.tsx, frontend/src/components/LoginFunctions/LoginFunctions.tsx, frontend/src/components/MenuFunctions/MenuFunctions.tsx
1. add padding in header
2. adjust login button, can show the full name.
3. turn all the words into Chinese in MenuFunction.
4. turn all the font bold
=> Frontend: Header UI adjustment

frontend/src/index.css, frontend/src/pages/HomePage/_components/Navbar.tsx
1. Turn the words into Chinese.
2. Add hover
=> Frontend: UI/navbar

frontend/src/pages/BuyPage/MealPage/MealCategoryPage/MealCategoryPage.tsx, frontend/src/pages/BuyPage/MealPage/MealShopListPage/MealShopListPage.tsx, frontend/src/pages/HomePage/_components/BlueSquare.tsx
1. make all border radius rounded
2. adjust 3 pages, homepage, mealcategory page, mealshoplist page
=> Frontend: adjust some radius div

frontend/src/pages/UserPage/SignInPage/SignInPage.tsx
1. Let Login Page UI style be similar with sign up page.
2. keep animation.
=> Frontend: Login Page UI adjustment, keeping animation

frontend/src/pages/UserPage/UserPage.tsx
=> Frontend: UI/user page

frontend/src/pages/BuyPage/MealPage/MealCategoryPage/_components/MealCategoryItem.css, frontend/src/pages/BuyPage/MealPage/MealCategoryPage/_components/MealCategoryItem.tsx, frontend/src/pages/BuyPage/MealPage/MealShopListPage/_components/MealShopListItem.css
1. MealShopList Page & MealCategoryPage UI adjustment
=> Frontend: UI/meal page

frontend/src/pages/SellPage/ShopPage/ShopBuyerpage.tsx
1. auto navigate to cart page when ordering meals.
2. meal order quantity +=1 when add the specific meals again.
=> Frontend: fix/cartpage

frontend/src/pages/OrderPage/SalerOrderPage/_components/SalerOrderItem.tsx
1. ask 確認/取消/完成 when press the buttons.
=> Frontend: SalerOrderPage UX adjustment

backend/src/controllers/order_repository.ts
=> Backend: fix link in sendEmail

frontend/src/pages/BuyPage/MealPage/AllMealsPage/Allmeals.tsx, frontend/src/pages/HomePage/_components/SearchBar/index.tsx, frontend/src/pages/HomePage/_components/SearchButton/index.tsx
=> Frontend: UI/search page

frontend/src/pages/BuyPage/MealPage/AllMealsPage/Allmeals.tsx, frontend/src/pages/BuyPage/MealPage/MealCategoryPage/_components/MealCategoryItem.css, frontend/src/pages/BuyPage/MealPage/MealCategoryPage/_components/MealCategoryItem.tsx, frontend/src/pages/SellPage/ShopPage/ShopBuyerpage.tsx, frontend/src/pages/SellPage/ShopPage/ShopEditPage.tsx, frontend/src/pages/SellPage/ShopPage/ShopPage.tsx, frontend/src/pages/UserPage/UserPage.tsx
1. turn all the words into Chinese
=> Frontend: UI/chinese wordings

frontend/src/pages/BuyPage/MealPage/AllMealsPage/Allmeals.tsx, frontend/src/pages/OrderPage/BuyerOrderPage/_components/BuyerOrderDetail.tsx, frontend/src/pages/SellPage/SalePage/StockPage/StockPage.tsx, frontend/src/pages/SellPage/ShopPage/MealDetail.tsx, frontend/src/pages/SellPage/ShopPage/ShopBuyerpage.tsx, frontend/src/pages/SellPage/ShopPage/ShopPage.tsx
1. Adjust MealItem UI in all-related pages, e.g. allMeals, shopEdit, shopbuyer.
2. Adjust some height, width, e.g. stock, shoppage, buyerOrderDetail.
everythiing looks well in XiangYi's laptop XD
=> Frontend: UI/final adjust
